//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ZhongTWind.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ZHONGTWIND_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDI_ICON_REDLIGHT               129
#define IDI_ICON_GREENLIGHT             130
#define IDI_ICON_BLUELIGHT              131
#define IDD_DLG_SYSPARAM                132
#define IDD_DLGIO                       133
#define IDD_DLG_WORKPLAN                134
#define IDR_LSTR_MENU                   135
#define IDD_INWORKING                   136
#define IDF_1                           1000
#define IDC_EDIT1                       1000
#define IDC_BUTTON_UPDATEDATA           1001
#define IDC_EDIT2                       1001
#define IDE_SANDWIDTH                   1002
#define IDE_CROSS_ANGLE                 1003
#define IDB_STARTWIND                   1003
#define IDB_SYSPARAMSET                 1004
#define IDE_BUFFLENGTH                  1004
#define IDC_BUTTON3                     1004
#define IDB_IOTEST                      1005
#define IDC_BUTTON4                     1005
#define IDE_SANDRATE                    1006
#define IDC_EDIT3                       1006
#define IDE_PIPE_TOTALLENGTH            1007
#define IDC_EDIT4                       1007
#define IDE_WINDMETHOD                  1008
#define IDL_CREATETASK                  1009
#define IDB_COMPUTE                     1010
#define IDB_TEST                        1010
#define IDB_MEASURESTART                1010
#define IDB_DELTASK                     1011
#define IDE_SPEEDUP_A_FACTOR            1012
#define IDB_ADDTASK                     1012
#define IDE_ZERO_LUOJU                  1016
#define IDE_SPEEDUP_A                   1017
#define IDE_CAR_SPEEDDOWNP              1018
#define IDE_CAR_DISTANCE_PER_R          1019
#define IDB_MAIN_NEG_DIR                1019
#define IDE_MAIN_AXE_LEVELFACTOR_5      1020
#define IDB_MAIN_POS_DIR                1020
#define IDE_MAIN_AXE_LEVELFACTOR_6      1021
#define IDB_MAIN_POS_DIR2               1021
#define IDE_MAIN_AXE_LEVELFACTOR_3      1022
#define IDB_MAIN_POS_DIR3               1022
#define IDE_MAIN_AXE_LEVELFACTOR_4      1023
#define IDB_MAIN_POS_DIR4               1023
#define IDE_MAIN_AXE_LEVELFACTOR_1      1024
#define IDE_MAIN_AXE_LEVELFACTOR_2      1025
#define IDE_MAIN_AXE_MAXSPEED           1026
#define IDE_CAR_MAXSPEED                1027
#define IDE_MAIN_AXE_PULSES             1028
#define IDE_CAR_PULSES                  1029
#define IDC_RADIO_MAINAXE_SPEED_1       1047
#define IDC_RADIO_MAINAXE_SPEED_4       1048
#define IDC_RADIO_MAINAXE_SPEED_2       1049
#define IDC_RADIO_MAINAXE_SPEED_5       1050
#define IDC_RADIO_MAINAXE_SPEED_3       1051
#define IDC_RADIO_MAINAXE_SPEED_6       1052
#define IDR_FIRM_SHA_WIDTH              1059
#define IDR_FIRM_CROSSANGLE             1061
#define IDR_FIRM_STOPANGLE              1063
#define IDC_RADIO_CUTOFF_POINTS         1065
#define IDC_RADIO_MAINAXE_SPEED_10      1066
#define IDC_RADIO_MAINAXE_SPEED_12      1067
#define IDC_RADIO_MAINAXE_SPEED_13      1068
#define IDC_RADIO_MAINAXE_SPEED_14      1069
#define IDB_RUN                         1192
#define IDLIST_SHOW_LAYER               1241
#define IDS_ICON_IN_1                   1248
#define IDS_ICON_IN_2                   1249
#define IDS_ICON_IN_3                   1250
#define IDS_ICON_IN_4                   1251
#define IDS_ICON_IN_5                   1252
#define IDS_ICON_IN_6                   1253
#define IDS_ICON_IN_7                   1254
#define IDS_ICON_IN_8                   1255
#define IDS_ICON_IN_9                   1256
#define IDS_ICON_IN_10                  1257
#define IDS_ICON_IN_11                  1258
#define IDS_ICON_IN_12                  1259
#define IDS_ICON_IN_13                  1260
#define IDS_ICON_IN_14                  1261
#define IDS_ICON_IN_15                  1262
#define IDS_ICON_IN_16                  1263
#define IDE_PIPEDIAMETER                1268
#define IDE_BANDI_WIDTH                 1269
#define IDB_INITIAL                     1270
#define IDB_SET_ZEROPOT                 1271
#define IDE_PUCENG_START                1272
#define IDB_STARTWORK                   1273
#define IDE_PIPE_DIAM                   1276
#define IDE_SHAPIAN_WIDTH               1277
#define IDE_START_POS                   1278
#define IDE_END_POS                     1279
#define IDE_START_STOPANGLE             1280
#define IDE_STOP_STOPANGLE              1281
#define IDE_END_STOPANGLE               1281
#define IDE_WIND_NUM                    1282
#define IDE_WORKING_OUTPUT              1284
#define IDE_WORKING_PROGRESS_1          1285
#define IDE_WORKING_PROGRESS_2          1286
#define IDE_WORKING_PROGRESS_3          1287
#define IDE_MAINAXE_SPEED               1288
#define IDE_MAINAXE_POS                 1289
#define IDE_MAINAXE_DIR                 1290
#define IDE_CAR_SPEED                   1291
#define IDE_CAR_POS                     1292
#define IDE_CAR_DIR                     1293
#define IDE_ALREADY_WINDNUM             1294
#define IDC_BUTTON1                     1296
#define IDB_STOP                        1296
#define IDC_BUTTON2                     1297
#define IDB_STOP_EMERG                  1297
#define IDE_DEBUG_OUT                   1298
#define IDM_DELETE                      32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
